coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 70%
        threshold: 2%
    patch:
      default:
        target: 70%
        threshold: 2%

parsers:
  javascript:
    enable_partials: yes

comment:
  layout: "header, diff, tree"
  behavior: default
  require_changes: false

ignore:
  - "src/__mocks__"
  - "tests/"
  - "**/*.d.ts"
  - "**/index.{js,ts}"