neverBuiltDependencies:
  - test-exclude
  - babel-plugin-istanbul

packages:
  - "packages/*"
  - "apps/*"
  - "waltodo-frontend"
  - "tests/testnet/setup"
ignoreBuiltDependencies:
  - bufferutil
  - sharp
  - unrs-resolver
  - utf-8-validate
