name: Coverage Badge

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10.11.0
          run_install: false

      - name: Setup pnpm PATH
        run: echo "$PNPM_HOME" >> $GITHUB_PATH

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline --link=false

      - name: Run tests with coverage
        run: pnpm test:coverage
        env:
          NODE_ENV: test
          SUI_NETWORK: testnet
          SUI_FULL_NODE_URL: 'https://fullnode.testnet.sui.io:443'

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          files: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          verbose: true

      - name: Create coverage badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: YOUR_GIST_ID_HERE
          filename: walrus_todo_coverage.json
          label: Coverage
          message: ${{ steps.coverage.outputs.percentage }}%
          color: 'green'
          namedLogo: jest

      - name: Update README with coverage badge
        run: |
          # This step happens automatically when using Codecov or other badge services
          echo "Coverage badge will be displayed from Codecov or your chosen badge service"
