name: Test Environment Setup

on:
  push:
    branches: [main, develop, wallet-fixes]
  pull_request:
    branches: [main]

jobs:
  setup-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install global dependencies
        run: |
          pnpm add -g oclif
          pnpm add -g typescript

      - name: Setup Sui CLI
        run: |
          curl -sSfL https://get.sui.io | sh -s -- --yes
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Setup Walrus CLI
        run: |
          curl -sSf https://docs.wal.app/setup/walrus-install.sh | sh
          echo "$HOME/.walrus/bin" >> $GITHUB_PATH

      - name: Create real testnet configuration
        run: |
          mkdir -p ~/.config/walrus
          cat > ~/.config/walrus/client_config.yaml << EOF
          aggregator: "https://aggregator.walrus-testnet.walrus.space"
          publisher: "https://publisher.walrus-testnet.walrus.space"
          context: "testnet"
          EOF

          # Create Sui testnet configuration
          mkdir -p ~/.sui/sui_config
          cat > ~/.sui/sui_config/client.yaml << EOF
          keystore:
            File: ~/.sui/sui_config/sui.keystore
          envs:
            - alias: testnet
              rpc: "https://fullnode.testnet.sui.io:443"
              ws: ~
          active_env: testnet
          active_address: ~
          EOF

      - name: Build project
        run: pnpm run build

      - name: Run unit tests
        run: pnpm test:unit
        env:
          NODE_ENV: test

      - name: Run command tests
        run: pnpm test:commands
        env:
          NODE_ENV: test
          SUI_NETWORK: testnet

      - name: Run integration tests
        run: pnpm test:integration
        env:
          NODE_ENV: test
          SUI_NETWORK: testnet
          SUI_FULL_NODE_URL: 'https://fullnode.testnet.sui.io:443'
          WALRUS_AGGREGATOR: 'https://aggregator.walrus-testnet.walrus.space'
          WALRUS_PUBLISHER: 'https://publisher.walrus-testnet.walrus.space'

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-${{ matrix.node-version }}
          path: |
            coverage/
            test-results/

      - name: Cache build artifacts
        uses: actions/cache@v4
        with:
          path: |
            dist/
            .oclif/
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-
