name: Tests

on:
  push:
    branches: [main, wallet-fixes]
  pull_request:
    branches: [main]

env:
  NODE_VERSION: '18.x'
  PNPM_VERSION: '10.11.0'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-key.outputs.key }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup pnpm PATH
        run: echo "$PNPM_HOME" >> $GITHUB_PATH

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Get pnpm store directory
        id: pnpm-cache-dir
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Generate cache key
        id: cache-key
        run: echo "key=${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v4
        id: pnpm-cache
        with:
          path: ~/.pnpm-store
          key: ${{ steps.cache-key.outputs.key }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        if: steps.pnpm-cache.outputs.cache-hit != 'true'
        run: pnpm install --no-frozen-lockfile --link=false

  test-unit:
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      # Environment variables for unit tests
      NODE_ENV: test
      TZ: UTC
      # Default test environment variables
      SUI_KEYSTORE_PATH: /tmp/test-keystore
      SUI_CLIENT_PATH: /tmp/test-client
      WALRUS_CONFIG_PATH: /tmp/test-walrus-config
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup pnpm PATH
        run: echo "$PNPM_HOME" >> $GITHUB_PATH

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Get pnpm store directory
        id: pnpm-cache-dir
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Clean node_modules before cache restore
        run: rm -rf **/node_modules

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Fresh install
        run: pnpm install --frozen-lockfile

      - name: Test Node.js compatibility
        run: ./scripts/test-node-compatibility.sh

      - name: Run unit tests
        run: pnpm test:unit -- --coverage --maxWorkers=4

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: unit-coverage
          path: coverage/

  test-commands:
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      NODE_ENV: test
      # AI integration test variables - using secrets
      XAI_API_KEY: ${{ secrets.XAI_API_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      # Test configuration
      ENABLE_AI_TESTS: ${{ secrets.XAI_API_KEY != '' && 'true' || 'false' }}
      OFFLINE_MODE: true
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup pnpm PATH
        run: echo "$PNPM_HOME" >> $GITHUB_PATH

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Get pnpm store directory
        id: pnpm-cache-dir
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Clean node_modules before cache restore
        run: rm -rf **/node_modules

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Fresh install
        run: pnpm install --frozen-lockfile

      - name: Run command tests
        run: pnpm test:commands -- --coverage --maxWorkers=2

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: commands-coverage
          path: coverage/

  test-integration:
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      NODE_ENV: test
      # Integration test configuration
      INTEGRATION_TESTS: true
      RATE_LIMIT_TESTS: true
      ERROR_SIMULATION: true
      # Real Sui and Walrus testnet configuration
      SUI_WALLET_PHRASE: ${{ secrets.SUI_WALLET_PHRASE }}
      SUI_NETWORK: testnet
      SUI_FULL_NODE_URL: 'https://fullnode.testnet.sui.io:443'
      WALRUS_AGGREGATOR: 'https://aggregator.walrus-testnet.walrus.space'
      WALRUS_PUBLISHER: 'https://publisher.walrus-testnet.walrus.space'
      WALRUS_CONFIG_PATH: /tmp/walrus-testnet-config
      # Real credentials for blockchain operations
      ENABLE_REAL_BLOCKCHAIN_TESTS: ${{ secrets.SUI_WALLET_PHRASE != '' && 'true' || 'false' }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup pnpm PATH
        run: echo "$PNPM_HOME" >> $GITHUB_PATH

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Get pnpm store directory
        id: pnpm-cache-dir
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Clean node_modules before cache restore
        run: rm -rf **/node_modules

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Fresh install
        run: pnpm install --frozen-lockfile

      - name: Run integration tests
        run: pnpm test:integration -- --coverage --maxWorkers=2

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: integration-coverage
          path: coverage/

  test-security:
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      NODE_ENV: test
      SECURITY_TESTS: true
      # Real blockchain security testing configuration
      SUI_NETWORK: testnet
      SUI_FULL_NODE_URL: 'https://fullnode.testnet.sui.io:443'
      SUI_WALLET_PHRASE: ${{ secrets.SUI_WALLET_PHRASE }}
      WALRUS_AGGREGATOR: 'https://aggregator.walrus-testnet.walrus.space'
      WALRUS_PUBLISHER: 'https://publisher.walrus-testnet.walrus.space'
      # Additional security test configurations
      ENABLE_CREDENTIAL_ROTATION_TESTS: true
      ENABLE_AUDIT_LOG_TESTS: true
      ENABLE_PERMISSION_TESTS: true
      ENABLE_REAL_BLOCKCHAIN_TESTS: ${{ secrets.SUI_WALLET_PHRASE != '' && 'true' || 'false' }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup pnpm PATH
        run: echo "$PNPM_HOME" >> $GITHUB_PATH

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Get pnpm store directory
        id: pnpm-cache-dir
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Clean node_modules before cache restore
        run: rm -rf **/node_modules

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Fresh install
        run: pnpm install --frozen-lockfile

      - name: Run security tests
        run: pnpm test -- tests/security --coverage --maxWorkers=2

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: security-coverage
          path: coverage/

  test-edge-cases:
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      NODE_ENV: test
      EDGE_CASE_TESTS: true
      # Real testnet configuration for edge case testing
      SUI_NETWORK: testnet
      SUI_FULL_NODE_URL: 'https://fullnode.testnet.sui.io:443'
      SUI_WALLET_PHRASE: ${{ secrets.SUI_WALLET_PHRASE }}
      WALRUS_AGGREGATOR: 'https://aggregator.walrus-testnet.walrus.space'
      WALRUS_PUBLISHER: 'https://publisher.walrus-testnet.walrus.space'
      # Configure edge case testing
      ENABLE_FUZZ_TESTS: true
      FUZZ_TEST_ITERATIONS: 100
      ENABLE_REAL_BLOCKCHAIN_TESTS: ${{ secrets.SUI_WALLET_PHRASE != '' && 'true' || 'false' }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup pnpm PATH
        run: echo "$PNPM_HOME" >> $GITHUB_PATH

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Get pnpm store directory
        id: pnpm-cache-dir
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Clean node_modules before cache restore
        run: rm -rf **/node_modules

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Fresh install
        run: pnpm install --frozen-lockfile

      - name: Run edge case tests
        run: |
          pnpm test -- tests/edge-cases --coverage --maxWorkers=2
          pnpm test -- tests/fuzz --coverage --maxWorkers=2

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: edge-cases-coverage
          path: coverage/

  combine-coverage:
    needs:
      [
        test-unit,
        test-commands,
        test-integration,
        test-security,
        test-edge-cases,
      ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download all coverage reports
        uses: actions/download-artifact@v4
        with:
          path: coverage-reports

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup pnpm PATH
        run: echo "$PNPM_HOME" >> $GITHUB_PATH

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies for coverage
        run: pnpm add -D nyc --link=false

      - name: Combine coverage reports
        run: |
          mkdir -p combined-coverage
          find coverage-reports -name 'lcov.info' -exec cp {} combined-coverage/ \;
          cd combined-coverage
          for i in *.info; do mv "$i" "${i%.info}_$(uuidgen).info"; done
          cd ..
          npx nyc merge combined-coverage coverage/lcov.info

      - name: Generate coverage report
        run: |
          npx nyc report --reporter=text --reporter=html

      - name: Upload combined coverage
        uses: actions/upload-artifact@v4
        with:
          name: combined-coverage
          path: coverage/

      - name: Check coverage thresholds
        run: |
          npx nyc check-coverage --branches 80 --functions 80 --lines 80 --statements 80 || echo "Coverage below threshold"

  build-check:
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup pnpm PATH
        run: echo "$PNPM_HOME" >> $GITHUB_PATH

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Get pnpm store directory
        id: pnpm-cache-dir
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Clean node_modules before cache restore
        run: rm -rf **/node_modules

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Fresh install
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm run build

      - name: Lint code
        run: pnpm run lint || echo "Linting not configured"

      - name: Type check
        run: pnpm run typecheck || echo "Type checking not configured"

  summary:
    needs:
      [
        test-unit,
        test-commands,
        test-integration,
        test-security,
        test-edge-cases,
        build-check,
        combine-coverage,
      ]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Test Summary
        run: |
          echo "## Test Suite Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Test Suite | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|------------|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| Unit Tests | ${{ needs.test-unit.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Command Tests | ${{ needs.test-commands.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Integration Tests | ${{ needs.test-integration.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Security Tests | ${{ needs.test-security.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Edge Case Tests | ${{ needs.test-edge-cases.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Build Check | ${{ needs.build-check.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Coverage Combination | ${{ needs.combine-coverage.result }} |" >> $GITHUB_STEP_SUMMARY